### ISSUE TITLE
win32 debug documentation link is broken

### ISSUE THREAD

**Issue by Alex-PLACET** [microsoft/windows-docs-rs#1]
[win32::debug](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/debug/index.html) is broken.
No issue to generate it on my machine.

**Comment by kennykerr** [comment]
Oh, I think that might be because of this. 😉 

https://github.com/microsoft/windows-docs-rs/blob/c105bd478d8750cb785a8ac8654ed0dee527495c/.gitignore#L2

**Comment by kennykerr** [comment]
I'll publish another update when I get a moment - thanks for letting me know!

**Comment by Alex-PLACET** [comment]
> Oh, I think that might be because of this. 😉
> 
> https://github.com/microsoft/windows-docs-rs/blob/c105bd478d8750cb785a8ac8654ed0dee527495c/.gitignore#L2

Good catch !

**Comment by kennykerr** [comment]
This has now been fixed.
